name: Create/update tag
on:
  push:
    branch: "master"
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: create Tagname
        run: |
          tagname="$(date '+%Y-%m-%d')"
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: $"$tagname"
          message: "$tagname release"
          
