name: Create/update tag
on:
  push:
    branches: "master"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up env var
        run:  echo "TAG=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
      - uses: rickstaa/action-create-tag@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG }}
          message: "${{ env.TAG }} release"
          
