name: Download and Update all

on:
  schedule:
    - cron: "11 3 * * *"

  workflow_dispatch:

jobs:
  update_page:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ./.github/workflows

    steps:
      - uses: actions/checkout@master
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: covid
          python-version: 3.9
          miniconda-version: "latest"
          channels: conda-forge,defaults
      - name: Install requirements from requirements.txt
        run: pip install -r ./requirements.txt
        working-directory: ./
      - name: Run Download scheduler
        run: python ./schedule.py
        continue-on-error: true
        working-directory: ./src/
      - name: process Fallzahlen
        run: python ./process_RKI_Covid_update.py
        continue-on-error: true
        working-directory: ./src/
        timeout-minutes: 60
      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ':/*.csv'
	  git add ':/*.json'
          git status -s
          git commit -m "update on $(date '+%Y-%m-%d')"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
